### ISSUE TITLE
fans speed change randomly

### ISSUE THREAD

**Issue by felixsanz** [audiohacked/OpenCorsairLink#120]
why, when running this command `OpenCorsairLink --device 0`, the fans speed up? and if running it again, speed down?

what's this magic about?

**Comment by audiohacked** [comment]
I just pushed some work that "should" prevent changes to the device on running.

**Comment by nick-s-b** [comment]
@audiohacked I just compiled the new version and I'm still seeing the same behavior:
````
Name            : opencorsairlink-git
Version         : 20180805-1
````
and:

````
$ sudo OpenCorsairLink --device 0
Dev=0, CorsairLink Device Found: H115i!

Vendor: Corsair
Product: H115i
Firmware: 2.8.0.0
Temperature 0: 32.10 C
Temperature 1: 32.10 C
Temperature 2: 32.10 C
Fan 0:	Mode 0x07
	Current/Max Speed 660/0 RPM
Pump:	Mode 0x00
	Current/Max Speed 2010/0 RPM
````
Fans rev up after the above command but if I run it again,

````
$ sudo OpenCorsairLink --device 0
Dev=0, CorsairLink Device Found: H115i!

Vendor: Corsair
Product: H115i
Firmware: 2.8.0.0
Temperature 0: 32.20 C
Temperature 1: 32.20 C
Temperature 2: 32.20 C
Fan 0:	Mode 0x07
	Current/Max Speed 1080/0 RPM
Pump:	Mode 0x00
	Current/Max Speed 1950/0 RPM
````

they slow down again.

I don't have Windows currently installed so OpenCorsairLink is the only way I can control the AIO. I haven't really messed with any OpenCorsairLink options and after the first time I ran OpenCorsairLink with `--device 0` option, it automatically lowered the fan/pump speeds to reasonable and quiet levels. I suspect that the pump can store settings on the device so I'm not sure if OpenCorsairLink can modify those.

Anyway, even with this small issue, OpenCorsairLink is a superb piece of work.  Without your code, I would never be able to run a decent AIO. And if there's any debug info I can provide, I'd be more than happy to do so. I know it's not easy supporting a piece of software like this so thank you so much for all the hard work!

**Comment by audiohacked** [comment]
Ok, I think what's happening is I have guards in place to prevent writing values to the device. And I wasn't setting the guards to "disabled". Someone please test and report back! @nick-s-b

**Comment by nick-s-b** [comment]
@audiohacked WOW! No more fans/pump changes! :D Querying with `sudo OpenCorsairLink --device 0` does not change fan speeds anymore! Thank you so much Sean!!!!
